global:
  resolve_timeout: 5m

route:
  receiver: 'slack-alert'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'slack-alert'
    slack_configs:
      - send_resolved: true
        channel: '#<channel-name>'
        username: 'SystemAlertManager'
        api_url: '<slack-webhook-url>'
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
